import "./Guide.css";

export default function Guide() {
  return (
    <div className="page">
      <div className="page-header">
        <h1 className="page-title">How to Use Skills Hub</h1>
        <p className="page-subtitle">
          Everything you need to know — from finding a skill to loading it into Claude
        </p>
      </div>

      <div className="guide-layout">
        <div className="guide-content">

          {/* Section 1 */}
          <section className="guide-section card">
            <div className="guide-section-header">
              <span className="guide-step-num">01</span>
              <h2>What is a Skill?</h2>
            </div>
            <p>
              A <strong>skill</strong> is a file that gives Claude a set of instructions, context, or behaviour for a specific task. When you load a skill into your Claude setup, Claude reads it as part of its instructions before responding to you.
            </p>
            <p>
              Think of skills as reusable templates. Instead of explaining how to format a report every time, someone writes a skill once — and everyone on the team can use it repeatedly.
            </p>

            <div className="guide-callout">
              <span>💡</span>
              <span>Skills come in two formats — <strong>MD</strong> and <strong>SKILL</strong> — which behave differently when uploading to this hub.</span>
            </div>

            <div className="file-format-table">
              <div className="file-format-row file-format-header">
                <div>Format</div>
                <div>What it is</div>
                <div>Auto-populate on upload?</div>
                <div>How to get one</div>
              </div>
              <div className="file-format-row">
                <div><span className="file-type-badge file-type-md">MD</span></div>
                <div>Plain text markdown file — human readable</div>
                <div><span className="yes-badge">✅ Yes</span> — name, description and tags are read automatically from the file</div>
                <div>Copy skill text from Claude, paste into a text editor, save as <code>skill-name.md</code></div>
              </div>
              <div className="file-format-row">
                <div><span className="file-type-badge file-type-skill">SKILL</span></div>
                <div>Binary format generated by Claude in Chrome</div>
                <div><span className="no-badge">✗ No</span> — binary format cannot be parsed, fill fields manually</div>
                <div>Exported directly from Claude in Chrome extension</div>
              </div>
            </div>

            <div className="guide-callout guide-callout-teal" style={{ marginTop: 0 }}>
              <span>✅</span>
              <span><strong>Recommendation:</strong> Save skills as <code>.md</code> files wherever possible. They're easier to share, read, and upload — and auto-populate saves you time.</span>
            </div>
          </section>

          {/* Section 2 */}
          <section className="guide-section card">
            <div className="guide-section-header">
              <span className="guide-step-num">02</span>
              <h2>How to save a Skill as an MD file</h2>
            </div>
            <p>Claude doesn't have a built-in export button, but saving a skill as a <code>.md</code> file is straightforward:</p>
            <div className="guide-steps">
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Copy from the Claude conversation</h4>
                  <p>When Claude generates a skill, it appears as a code block. Click <strong>Copy</strong> on that block.</p>
                </div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Paste into a text editor</h4>
                  <p>Open TextEdit, VS Code, or any plain text editor. Paste the content.</p>
                </div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Save as .md</h4>
                  <p>Save the file and type the <code>.md</code> extension manually — e.g. <code>pdf-extractor.md</code>. Make sure it's saved as plain text, not rich text.</p>
                </div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Upload to the hub</h4>
                  <p>Drop it into the Upload page — fields will auto-populate from the file content.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Section 3 */}
          <section className="guide-section card">
            <div className="guide-section-header">
              <span className="guide-step-num">03</span>
              <h2>Finding a Skill</h2>
            </div>
            <div className="guide-steps">
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Browse the library</h4>
                  <p>Go to <strong>Discover</strong> to see all available skills. Search by keyword, tag, or author name.</p>
                </div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Describe your problem</h4>
                  <p>Go to <strong>AI Match</strong> and type what you're trying to do in plain English. The AI will recommend the best matching skills and flag which ones work well together.</p>
                </div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Download the file</h4>
                  <p>Click <strong>Download</strong> on any skill card. The file saves to your Downloads folder in its original format.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Section 4 */}
          <section className="guide-section card">
            <div className="guide-section-header">
              <span className="guide-step-num">04</span>
              <h2>Loading a Skill into Claude</h2>
            </div>
            <p>Once you've downloaded a skill file, here's how to use it:</p>

            <div className="guide-method">
              <div className="guide-method-header">
                <span className="method-badge method-a">Method A</span>
                <h4>Paste into your Claude Project <span style={{fontWeight:400, color:"var(--muted)"}}>— Recommended</span></h4>
              </div>
              <p>Best for skills you use regularly across an entire project.</p>
              <ol className="guide-numbered">
                <li>Open the <code>.md</code> or <code>.skill</code> file — for MD files use any text editor; for SKILL files use Claude in Chrome</li>
                <li>Copy all the text content</li>
                <li>In Claude, open your <strong>Project</strong> and go to <strong>Project Instructions</strong></li>
                <li>Paste the skill content and save</li>
              </ol>
              <div className="guide-callout guide-callout-teal">
                <span>✅</span>
                <span>Everyone in the project benefits automatically — no need to re-upload each conversation.</span>
              </div>
            </div>

            <div className="guide-method">
              <div className="guide-method-header">
                <span className="method-badge method-b">Method B</span>
                <h4>Upload the file directly in a chat</h4>
              </div>
              <p>Use this for one-off tasks where you need the skill just for that conversation.</p>
              <ol className="guide-numbered">
                <li>Open a new Claude conversation</li>
                <li>Click the <strong>paperclip / attachment icon</strong> in the message bar</li>
                <li>Select your downloaded skill file</li>
                <li>Type your request — Claude will read the skill before responding</li>
              </ol>
              <div className="guide-callout">
                <span>💡</span>
                <span>You can attach multiple skill files at once if your task needs more than one.</span>
              </div>
            </div>

            <div className="guide-method">
              <div className="guide-method-header">
                <span className="method-badge method-c">Method C</span>
                <h4>Paste the content at the start of a message</h4>
              </div>
              <p>Simplest option — no file handling needed. Only works with <span className="file-type-badge file-type-md" style={{fontSize:"0.7rem"}}>MD</span> files since SKILL files are binary.</p>
              <ol className="guide-numbered">
                <li>Open the <code>.md</code> file and copy all the text</li>
                <li>In your Claude message, paste the skill content first</li>
                <li>Then write your actual request below it and send</li>
              </ol>
            </div>
          </section>

          {/* Section 5 */}
          <section className="guide-section card">
            <div className="guide-section-header">
              <span className="guide-step-num">05</span>
              <h2>Uploading Your Own Skill</h2>
            </div>
            <div className="guide-steps">
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div><h4>Go to Upload Skill</h4><p>Click <strong>Upload Skill</strong> in the top navigation.</p></div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div>
                  <h4>Drop your file</h4>
                  <p>Both <span className="file-type-badge file-type-md" style={{fontSize:"0.7rem"}}>MD</span> and <span className="file-type-badge file-type-skill" style={{fontSize:"0.7rem"}}>SKILL</span> files are accepted. MD files will auto-populate the fields below — SKILL files require manual entry.</p>
                </div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div><h4>Review and complete the fields</h4><p>Check the auto-populated fields or fill them in manually. A good description makes your skill easier to find via search and AI matching.</p></div>
              </div>
              <div className="guide-step">
                <div className="guide-step-dot" />
                <div><h4>Submit</h4><p>Click Upload — your skill appears in the library immediately.</p></div>
              </div>
            </div>
          </section>

          {/* Section 6 */}
          <section className="guide-section card">
            <div className="guide-section-header">
              <span className="guide-step-num">06</span>
              <h2>Tips for Using Skills Effectively</h2>
            </div>
            <div className="guide-tips-grid">
              {[
                { icon: "🔗", title: "Combine skills", body: "The AI Matcher will tell you which skills work well together. Loading two or three complementary skills at once is often more powerful than one alone." },
                { icon: "📝", title: "Read before loading", body: "Skim the file before adding it to a project. Understanding what a skill does helps you write better prompts alongside it." },
                { icon: "💾", title: "Save as MD", body: "Whenever possible, save skills as .md files rather than .skill. They're human-readable, easier to share, and auto-populate on upload." },
                { icon: "🗂️", title: "Use Projects", body: "If you use a skill daily, put it in a Claude Project rather than uploading it each time. This saves effort and keeps your workspace consistent." },
                { icon: "💬", title: "Be specific with AI Match", body: "The more detail you give the AI Matcher, the better the recommendations. Include what your input looks like and what output you need." },
                { icon: "🤝", title: "Share what you build", body: "If you tweak a skill or build one from scratch and it works well, upload it. That's how the library grows." },
              ].map(({ icon, title, body }) => (
                <div key={title} className="guide-tip">
                  <span className="guide-tip-icon">{icon}</span>
                  <h4>{title}</h4>
                  <p>{body}</p>
                </div>
              ))}
            </div>
          </section>

        </div>

        <nav className="guide-toc card">
          <div className="guide-toc-title">On this page</div>
          <ul>
            {[
              "What is a Skill?",
              "Saving as MD file",
              "Finding a Skill",
              "Loading into Claude",
              "Uploading Your Skill",
              "Tips",
            ].map((item, i) => (
              <li key={item}>
                <span className="toc-num">0{i + 1}</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </div>
  );
}
